export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
    DATA_UPDATED: "PROFILE_DATA_UPDATED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
    LOGOUT_DATA: "PROFILE_REMOVE_DATA",
  },
  author: {
    DATA_FETCHING: "AUTHOR_DATA_FETCHING",
    DATA_FETCHED: "AUTHOR_DATA_FETCHED",
    DATA_FETCHED_ERROR: "AUTHOR_DATA_FETCHED_ERROR",
  },
};
